"""
Exercise 08: Online vs Offline RL Data Flow

Difficulty: Medium
Framework: numpy

Background:
    In RLHF training, there are two major paradigms:

    1. Online RL (slime train.py default):
       generate -> train -> update policy -> generate with new policy -> ...
       Data is always fresh (generated by current policy), but slower.

    2. Offline RL (or async, slime train_async.py):
       Use a fixed dataset or generate asynchronously while training.
       Faster throughput, but data may be "stale" (from an older policy).

    Data staleness is measured by the gap between the policy version that
    generated the data and the current policy version.

    Reference:
    - train.py: synchronous generate -> train loop
    - train_async.py: overlaps generation with training (next rollout
      starts before current training finishes)

Implement:
    OnlineScheduler: simulates synchronous online RL loop
    OfflineScheduler: simulates offline training with fixed data
    AsyncScheduler: simulates async overlap (like train_async.py)

Each scheduler should track:
    - policy_version: incremented after each train step
    - data_log: list of (step, data_policy_version) tuples
    - staleness at each step = current_policy_version - data_policy_version

Methods:
    run(num_steps) -> dict with 'data_log', 'staleness_history', 'avg_staleness'
"""

import numpy as np


class OnlineScheduler:
    """Synchronous online RL: generate with current policy, then train."""

    def __init__(self):
        self.policy_version = 0

    def run(self, num_steps: int) -> dict:
        """Simulate num_steps of online training.

        At each step:
        1. Generate data using current policy_version
        2. Train on that data
        3. Increment policy_version

        Returns:
            dict with:
            - 'data_log': list of (step, data_policy_version)
            - 'staleness_history': list of staleness values per step
            - 'avg_staleness': float, mean staleness
        """
        # TODO: Implement online training loop
        # Hint: staleness should always be 0 (data is from current policy)
        raise NotImplementedError("Implement OnlineScheduler.run")


class OfflineScheduler:
    """Offline RL: train multiple epochs on fixed data from initial policy."""

    def __init__(self):
        self.policy_version = 0

    def run(self, num_steps: int) -> dict:
        """Simulate num_steps of offline training.

        Data was generated at policy_version=0 (fixed dataset).
        At each step:
        1. Train on the fixed data (policy_version=0)
        2. Increment policy_version

        Returns:
            Same format as OnlineScheduler.run
        """
        # TODO: Implement offline training loop
        # Hint: staleness increases by 1 each step (data always from version 0)
        raise NotImplementedError("Implement OfflineScheduler.run")


class AsyncScheduler:
    """Async RL: overlap generation with training (like train_async.py).

    Pattern: at each step, we train on data from the *previous* generation
    while the next generation runs in parallel. The data used for training
    was generated by policy_version at the time generation started.
    """

    def __init__(self, update_interval: int = 1):
        """
        Args:
            update_interval: how often to refresh data (sync new generation).
                            With interval=1, data is 1 step stale.
                            With interval=k, data can be up to k steps stale.
        """
        self.policy_version = 0
        self.update_interval = update_interval

    def run(self, num_steps: int) -> dict:
        """Simulate num_steps of async training.

        The async pattern (matching train_async.py):
        - Generation for step 0 starts before training
        - At each step, train on the last completed generation
        - New generation starts after weight update (every update_interval steps)
        - Data generated at policy version V is used until next refresh

        Returns:
            Same format as OnlineScheduler.run
        """
        # TODO: Implement async training loop
        # Hint 1: Track data_gen_version (policy version when data was generated)
        # Hint 2: data_gen_version starts at 0 (initial generation)
        # Hint 3: After every update_interval steps, start new generation
        #         with current policy_version as new data_gen_version
        # Hint 4: staleness = policy_version - data_gen_version
        raise NotImplementedError("Implement AsyncScheduler.run")
